# -*- coding: utf-8 -*-
"""Prodigy_ML_01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZSfGE2zuzVhLwQ6SqWiR4ilvKTsH08Hc
"""

import os
print(os.listdir())

import zipfile

with zipfile.ZipFile("/content/sample_data/train.zip", "r") as zip_ref:
    zip_ref.extractall()

with zipfile.ZipFile("/content/sample_data/test.zip", "r") as zip_ref:
    zip_ref.extractall()

print("Files extracted successfully")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score


train_data = pd.read_csv("train.csv")
test_data = pd.read_csv("test.csv")

print("Training Dataset:\n")
print(train_data.head())

print("\nTesting Dataset:\n")
print(test_data.head())


Xtr = train_data[['GrLivArea']].values


ytr = train_data['SalePrice'].values



Xte = test_data[['GrLivArea']].values



model = LinearRegression()
model.fit(Xtr, ytr)



yp = model.predict(Xte)



print("\nModel Details:\n")

print(f"Slope      : {model.coef_[0]}")
print(f"Intercept  : {model.intercept_}")

print(
    f"Equation   : "
    f"SalePrice = {model.coef_[0]:.4f} * GrLivArea + {model.intercept_:.4f}"
)


xline = np.linspace(
    Xtr.min(),
    Xtr.max(),
    200
).reshape(-1, 1)

plt.figure(figsize=(8,5))

plt.scatter(Xtr, ytr, label='Training Data')

plt.plot(
    xline,
    model.predict(xline),
    linewidth=2,
    label='Regression Line'
)

plt.xlabel('Ground Living Area')
plt.ylabel('Sale Price')

plt.title('House Price Prediction')

plt.legend()
plt.grid(True)
plt.show()



plt.figure(figsize=(8,5))

plt.plot(yp[:100])

plt.xlabel('Test Houses')
plt.ylabel('Predicted Sale Price')

plt.title('Predicted House Prices')

plt.grid(True)
plt.show()



submission = pd.DataFrame({
    'Id': test_data['Id'],
    'PredictedSalePrice': yp
})

submission.to_csv("predicted_prices.csv", index=False)

print("\nPredictions saved to predicted_prices.csv")